config/routes.rb
Rails.application.routes.draw do
  root 'wizards#index'

  # post "/wizards/search" to "/wizards/#search"
  
  resources :wizards, only: [:index, :show, :new, :create, :edit, :update] do
    resources :spells, only: [:new, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/balloon_animal.rb
class BalloonAnimal < ApplicationRecord
  has_many :reviews

  validates :animal, presence: true
  # validates :color, presence: true
end

app/models/centaur.rb
class Centaur < ApplicationRecord

end

app/models/manticore.rb
class Manticore < ApplicationRecord 
    validates :name, presence: true 
    validates :ferocity, presence: true
end

app/models/monster.rb
class Monster < ApplicationRecord
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :balloon_animal

end

app/models/spell.rb
class Spell < ApplicationRecord
  validates :name, presence: true

  belongs_to :wizard
end

app/models/spindrift.rb
class Spindrift 


  edsnfasdff 

end

app/models/unicorn.rb
class Unicorn < ApplicationRecord
  belongs_to :rider
  # validates :rider_id, presence: true

end

app/models/wizard.rb
class Wizard < ApplicationRecord
  has_many :spells
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/balloon_animals_controller.rb
class BalloonAnimalsController < ApplicationController

  def index
    @balloon_animals = BalloonAnimal.all
    # render :index
  end

  def show
    @balloon_animal = BalloonAnimal.find(params[:id])
  end

  def new 
    @balloon_animal = BalloonAnimal.new
    # render :new 
  end

  def create 
    @balloon_animal = BalloonAnimal.new(balloon_animal_params)

    if @balloon_animal.save 
      flash[:notice] = "good job"

      redirect_to @balloon_animal
      # redirect "/balloon_animals/#{@balloon_animal}.id"
    else 
      flash[:notice] = @balloon_animal.errors.full_messages.to_sentence
      render :new
    end

  end

  private 

  def balloon_animal_params 
    params.require(:balloon_animal).permit(:animal, :color)
  end

  def hello 
    return "hello"
  end



end

app/controllers/centaurs_controller.rb
class CentaursController < ApplicationController

  def index 
    @centaurs = Centaur.all
  end

  def show 
    @centaur = Centaur.find(params[:id])
  end 

  

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/manticores_controller.rb
class ManticoresController < ApplicationController 

    def index 
        @manticores = Manticore.all
        # render :"manticores/index.html.erb"
    end

    def show 
        @manticore = Manticore.find(params[:id])
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @balloon_animal = BalloonAnimal.find(params[:balloon_animal_id])
    @review = Review.new
  end

  def create 
    @review = Review.new(body: params[:review][:body])
    @balloon_animal = BalloonAnimalfind(params[:balloon_animal_id]))
    @review.balloon_animal = @balloon_animal

    if @review.save
      redirect_to @balloon_animal
    else 
      render :new 
    end
  end

  def show 
    @review = Review.find(params[:id])
    @balloon_animal = @review.balloon_animal
  end

  def index 
    @reviews = Review.all 

    # else 
    @balloon_animal = BalloonAnimal.find(params[:balloon_animal_id])
    @reviews = @balloon_animal.reviews
    
  end





end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  def new
    # binding.pry
    @wizard = Wizard.find(params[:wizard_id])
    @spell = Spell.new
  end

  def create
    # binding.pry
    @wizard = Wizard.find(params[:wizard_id])
    @spell = Spell.new(spell_params)
    @spell.wizard = @wizard
    if @spell.save
      redirect_to @wizard
    else
      render :new
    end
  end

  private

  def spell_params
    params.require(:spell).permit(:name, :spell_type)
  end
end

app/controllers/unicorns_controller.rb
class UnicornsController < ApplicationController

  def index
    @unicorns = Unicorn.all
  end

end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController

  def index
    @wizards = Wizard.all
    # render :"views/wizards/index.html.erb"
  end

  def show
    @wizard = Wizard.find(params[:id])
  end

  def new
    @wizard = Wizard.new
  end

  def create
    # binding.pry
    @wizard = Wizard.new(wizard_params)
    if @wizard.save
      # redirect_to "/wizards"
      redirect_to wizards_path
    else
      render :new
    end
  end

  def edit
    @wizard = Wizard.find(params[:id])
  end

  def update
    @wizard = Wizard.find(params[:id])

    if @wizard.update(wizard_params)
      # redirect_to "wizards/#{@wizard.id}"
      redirect_to @wizard
      # redirect_to wizard_path(@wizard)
    else
      render :edit
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
  def wizard_params
    params.require(:wizard).permit(:name, :age, :title)
  end
end

app/helpers/cyborbs_helper.rb
module CyborbsHelper
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/views/balloon_animals/index.html.erb
<% @balloon_animals.each do |balloon_animal| %>
<li>
  <%= link_to(balloon_animal.animal, balloon_animal_path(balloon_animal))  %>
</li>
<% end %>

app/views/balloon_animals/new.html.erb
<%= form_for(@balloon_animal) do |f| %>
  <%= f.label :animal %>
  <%= f.text_field :animal %>

  <%= f.label :color %>
  <%= f.text_field :color %>

  <%= f.submit %>
<% end %>

app/views/balloon_animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @balloon_animal.animal %>
</p>

<p>
  <strong>Color:</strong>
  <%= @balloon_animal.color %>
</p>

<%= link_to('New Review Form For Animal', new_balloon_animal_review_path(@balloon_animal)) %>

app/views/centaurs/index.html.erb
<h1>Centaurs Index</h1>

<% @centaurs.each do |centaur| %>
<li>
  <%= link_to(centaur.name, centaur_path(centaur)) %>
</li>
  
<% end%>

app/views/centaurs/show.html.erb
<h1>Centaur Show Page for <%= @centaur.name %></h1>

<div>
<%= @centaur.favorite_tree_nut %> | <%= @centaur.ride_sharing %>
</div>

app/views/homes/index.html.erb
<div id="app">

</div>

app/views/manticores/index.html.erb
<h1>Manticores</h1>

<% @manticores.each do |manticore| %>
    <li>
        <%= link_to(manticore.name, manticore_path(manticore.id)) %>
    </li>
<% end %>

app/views/manticores/show.html.erb
<h1> <%= @manticore.name %> </h1>
<p> Age: <%= @manticore.age %> </p>
<p> Ferocity: <%= @manticore.ferocity %> </p>

app/views/reviews/new.html.erb
<h1> New Review for <%= @balloon_animal.animal %></h1>

<%= form_for [@balloon_animal, @review] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/spells/index.html.erb
<h2>Spells Page</h2>

<% if @wizard %>
  <h3> <%= @wizard.name %> </h3>
<% end %>

<% @spells.each do |spell| %>
  <li>
    <%= spell.name %>
  </li>
<% end %>

app/views/spells/new.html.erb
<h1>Add a New Spell</h1>

<%= form_for([@wizard, @spell]) do |f| %>
  <%= f.label "Name:" %>
  <%= f.text_field :name %>

  <%= f.label "Spell Type:" %>
  <%= f.text_field :spell_type %>

  <%= f.submit %>
<% end %>

app/views/unicorns/index.html.erb
<% @unicorns.each do |unicorn| %>
  <li>
    <%= unicorn.name %>
  </li>
<% end %>

app/views/unicorns/new.html.erb
New Unicorn Form

<form class="" action="index.html" method="post">
  <input type="text" name="" value="">
  <input type="submit" name="" value="">
</form>

app/views/wizards/edit.html.erb
<h1>Editing Wizard</h1>

<%= form_for(@wizard) do |f| %>
  <%= f.label "Name:" %>
  <%= f.text_field :name %>

  <%= f.label "Wizard Title:" %>
  <%= f.text_field :title %>

  <%= f.label "Age:" %>
  <%= f.text_field :age %>

  <%= f.submit "Edit your Wizard" %>
<% end %>

<%= link_to 'Show', @wizard %> |
<%= link_to 'Back', wizards_path %>

app/views/wizards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wizards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wizards.each do |wizard| %>
      <tr>
        <td><%= wizard.name %></td>
        <td><%= wizard.title %></td>
        <td><%= wizard.age %></td>
        <td><%= link_to 'Show', wizard %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Wizard', new_wizard_path %>

app/views/wizards/new.html.erb
<h1>New Wizard</h1>

<%= form_for(@wizard) do |f| %>
  <%= f.label "Name:" %>
  <%= f.text_field :name %>

  <%= f.label "Wizard Title:" %>
  <%= f.text_field :title %>

  <%= f.label "Age:" %>
  <%= f.text_field :age %>

  <%= f.submit %>
<% end %>

<%= link_to 'Back', wizards_path %>

app/views/wizards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wizard.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @wizard.title %>
</p>

<p>
  <strong>Age:</strong>
  <%= @wizard.age %>
</p>

<div>
  <% @spells.each do |spell| %>
  <li>
    <%= spell.name  %>
  </li>
  <% end  %>
</div>

<%= link_to 'Add New Spell', new_wizard_spell_path(@wizard) %>

<%= link_to 'Back', wizards_path %>